[package]
name = "image-server"
version = "0.1.0"
authors = ["Michael Wolf <mjwolf@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.7"
mime = "0.3.16"
formdata = "0.13.0"
